print("What is your name")
name = input()
print("How old are you (in years)?")
age = int(input())
print("How tall are you (in metres)?")
height = float(input())
print("How much do you weigh (in kilograms)?")
weight = int(input())
print()
BMI = weight/(height*height)
print(name + " you are " + str(age) + " years old and your bmi is " + str(BMI) + ".")